name: pulselab
description: "A prototype app about blood clinic, developed for the Human-Computer Interaction discipline."
publish_to: "none" # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  intl: ^0.20.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.14.1
  flutter_lints: ^4.0.0
  rename: ^3.0.2

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icons/app_icon.png"
  remove_alpha_ios: true
  min_sdk_android: 21
  adaptive_icon_foreground: "assets/icons/app_icon.png"
  adaptive_icon_background: "#ffffff"

flutter:
  uses-material-design: true
  assets:
    - assets/icons/app_icon.png
    - assets/users/photo_ee52c78b-a95c-424d-9dac-1eae79732f3c.jpg
  fonts:
    - family: PulseLab
      fonts:
        - asset: assets/fonts/PulseLab.ttf
